language: cpp

os:
  - osx

compiler:
  - clang
    
before_install: true

install:
  - brew update
  - brew install gcc
  - brew install python
  - brew install ocaml

before_script:
  - git clone https://github.com/wintersteiger/z3test.git z3test --branch build-ng

env: true

script:
  - git rev-parse --abbrev-ref HEAD
  - git show-ref --abbrev=12 refs/heads/build-ng
  - pwd
  - ls -l
  - export Z3DIR=`pwd`
  - cd z3test
  - python scripts/smalltest.py
  - if [[ "$?" == "0" ]]; then
      cd ..    ;
      python scripts/mk_unix_dist.py --githash ;
    fi

after_success: true

after_failure: true

after_script: true
