language: cpp
compiler:
  - gcc
  - clang

before_install: true

install:
  - sudo apt-get install python
  - sudo apt-get install ocaml

before_script: 
  - git clone https://github.com/wintersteiger/z3test.git z3test --branch build-ng

env: MAKEJOBS=4

script:
  - jdk_switcher use oraclejdk8
  - git rev-parse --abbrev-ref HEAD
  - git show-ref --abbrev=12 refs/heads/build-ng
  - pwd
  - ls -l
  - export Z3DIR=`pwd`
  - cd z3test
  - python scripts/smalltest.py
  - cd ..
  - python scripts/mk_unix_dist.py --githash

after_success: true

after_failure: true

after_script: true