language: cpp

os:
  - linux
  - osx

jdk:
  - openjdk7
  
compiler:
  - gcc
  - clang

before_install: true

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      sudo apt-get install python ;
      sudo apt-get install ocaml ocaml-findlib;
    elif [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew update ;
      brew install gcc ;
      brew install python ;
	  brew install ocaml ;
    fi

before_script: 
  - git clone https://github.com/wintersteiger/z3test.git z3test --branch build-ng

env: true

script:
  - git rev-parse --abbrev-ref HEAD
  - git show-ref --abbrev=12 refs/heads/build-ng
  - pwd
  - ls -l
  - export Z3DIR=`pwd`
  - cd z3test
  - python scripts/smalltest.py
  - cd ..
  - python scripts/mk_unix_dist.py --githash

after_success: true

after_failure: true

after_script: true